In [1]:
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), "src"))

In [2]:
import sh_ssw_methods as ssw

In [3]:
import xarray as xr

In [4]:
import importlib as imp

In [35]:
imp.reload(ssw);

1. ozone threshold

In [6]:
years = ("1980", "2020")
lat_band=(-90.0,-65.0)
thresh_du=40.0
min_persist_days=3
min_gap_days=20
data_source="MERRA2"

In [7]:
# open sample total column ozone data
tco3_path =  os.getcwd()+ "/data/" +"tco3_MERRA2.nc"
xtco3 = xr.open_dataset(tco3_path)

In [8]:
xtco3

<xarray.Dataset> Size: 5MB
Dimensions:  (time: 16802, lat: 73)
Coordinates:
  * time     (time) datetime64[ns] 134kB 1979-07-01 1979-07-02 ... 2025-06-30
  * lat      (lat) float32 292B -90.0 -87.5 -85.0 -82.5 ... 82.5 85.0 87.5 90.0
Data variables:
    tcO3     (time, lat) float32 5MB ...

In [25]:
# select years
da = xtco3['tcO3'].sel(time=slice(*years))

In [26]:
# detect events
tco3_events_df, tco3_dates = ssw.detect_ozone_threshold(da)

In [27]:
tco3_dates

array(['1980-11-26T00:00:00.000000000', '1981-09-21T00:00:00.000000000',
       '1981-11-20T00:00:00.000000000', '1982-10-04T00:00:00.000000000',
       '1983-11-03T00:00:00.000000000', '1984-11-02T00:00:00.000000000',
       '1986-09-05T00:00:00.000000000', '1986-11-13T00:00:00.000000000',
       '1988-09-24T00:00:00.000000000', '1988-10-25T00:00:00.000000000',
       '1991-11-18T00:00:00.000000000', '1994-08-16T00:00:00.000000000',
       '2000-11-06T00:00:00.000000000', '2002-09-22T00:00:00.000000000',
       '2003-11-03T00:00:00.000000000', '2005-11-12T00:00:00.000000000',
       '2012-10-09T00:00:00.000000000', '2013-11-02T00:00:00.000000000',
       '2016-11-23T00:00:00.000000000', '2017-11-07T00:00:00.000000000',
       '2019-09-08T00:00:00.000000000'], dtype='datetime64[ns]')

In [28]:
tco3_events_df

,date,method,definition,data_source,threshold,level_hpa,latitude,lat_band,notes,ozone_onset_DU
0,1980-11-26,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,44.135197
1,1981-09-21,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.728470
2,1981-11-20,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,47.080032
3,1982-10-04,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,42.314781
4,1983-11-03,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.157120
5,1984-11-02,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.721432
6,1986-09-05,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,42.500244
7,1986-11-13,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,45.134018
8,1988-09-24,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.411381
9,1988-10-25,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,45.098133
10,1991-11-18,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.173271
11,1994-08-16,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.583092
12,2000-11-06,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.639286
13,2002-09-22,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,58.906464
14,2003-11-03,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.034882
15,2005-11-12,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,47.487080
16,2012-10-09,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.686127
17,2013-11-02,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.269764
18,2016-11-23,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.477310
19,2017-11-07,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,42.184422
20,2019-09-08,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.131966

2. u wind decel

In [30]:
# open sample total column ozone data
u1060_path =  os.getcwd()+ "/data/" +"u1060s_era5_1959_2023.nc"
xu1060 = xr.open_dataset(u1060_path)

In [31]:
xu1060

<xarray.Dataset> Size: 1MB
Dimensions:  (time: 94964)
Coordinates:
  * time     (time) datetime64[ns] 760kB 1959-01-01 ... 2023-12-31T18:00:00
    lat      float64 8B ...
    plev     float64 8B ...
Data variables:
    u1060S   (time) float32 380kB ...

In [32]:
# select years
da = xu1060['u1060S'].sel(time=slice(*years))

In [36]:
# detect events
u1060_events_df, u1060_dates = ssw.detect_u_decel_events(da)

In [37]:
u1060_dates

DatetimeIndex(['1984-10-03 18:00:00', '1990-10-04 00:00:00',
               '1991-09-21 12:00:00', '1992-09-02 18:00:00',
               '1997-11-02 00:00:00', '2000-09-22 12:00:00',
               '2002-08-21 00:00:00', '2002-09-20 18:00:00',
               '2003-10-02 12:00:00', '2005-09-19 06:00:00',
               '2007-09-17 18:00:00', '2008-10-11 00:00:00',
               '2016-09-07 00:00:00', '2019-09-04 12:00:00'],
              dtype='datetime64[ns]', freq=None)

In [38]:
u1060_events_df

,date,method,definition,data_source,threshold,level_hpa,latitude,lat_band,notes,drop_val
0,1984-10-03 18:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-29.089287
1,1990-10-04 00:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-22.772488
2,1991-09-21 12:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-22.080673
3,1992-09-02 18:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-21.866943
4,1997-11-02 00:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-22.467836
5,2000-09-22 12:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-26.756741
6,2002-08-21 00:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-29.735279
7,2002-09-20 18:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-30.976959
8,2003-10-02 12:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-24.091248
9,2005-09-19 06:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-32.078751
10,2007-09-17 18:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-21.097618
11,2008-10-11 00:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-21.414627
12,2016-09-07 00:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-21.749329
13,2019-09-04 12:00:00,u_wind_decel,decel_wdw10_ratio1.2_thr-2perday,,-2.0ms-1/day,None,None,<NA>,min_gap=20d; window=10d,-21.301983