In [1]:
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), "src"))

In [2]:
import sh_ssw_methods as ssw

In [3]:
import xarray as xr

In [4]:
import importlib as imp

In [5]:
imp.reload(ssw);

1. ozone threshold

In [6]:
years = ("1980", "2020")
lat_band=(-90.0,-65.0)
thresh_du=40.0
min_persist_days=3
min_gap_days=20
data_source="MERRA2"

In [7]:
# open sample total column ozone data
tco3_path =  os.getcwd()+ "/data/" +"tco3_MERRA2.nc"
xtco3 = xr.open_dataset(tco3_path)

In [8]:
xtco3

<xarray.Dataset> Size: 5MB
Dimensions:  (time: 16802, lat: 73)
Coordinates:
  * time     (time) datetime64[ns] 134kB 1979-07-01 1979-07-02 ... 2025-06-30
  * lat      (lat) float32 292B -90.0 -87.5 -85.0 -82.5 ... 82.5 85.0 87.5 90.0
Data variables:
    tcO3     (time, lat) float32 5MB ...

In [9]:
# select years
da = xtco3['tcO3'].sel(time=slice(*years))

In [10]:
# detect events
tco3_events_df, tco3_dates = ssw.detect_ozone_threshold(da)

In [11]:
tco3_dates

array(['1980-11-26T00:00:00.000000000', '1981-09-21T00:00:00.000000000',
       '1981-11-20T00:00:00.000000000', '1982-10-04T00:00:00.000000000',
       '1983-11-03T00:00:00.000000000', '1984-11-02T00:00:00.000000000',
       '1986-09-05T00:00:00.000000000', '1986-11-13T00:00:00.000000000',
       '1988-09-24T00:00:00.000000000', '1988-10-25T00:00:00.000000000',
       '1991-11-18T00:00:00.000000000', '1994-08-16T00:00:00.000000000',
       '2000-11-06T00:00:00.000000000', '2002-09-22T00:00:00.000000000',
       '2003-11-03T00:00:00.000000000', '2005-11-12T00:00:00.000000000',
       '2012-10-09T00:00:00.000000000', '2013-11-02T00:00:00.000000000',
       '2016-11-23T00:00:00.000000000', '2017-11-07T00:00:00.000000000',
       '2019-09-08T00:00:00.000000000'], dtype='datetime64[ns]')

In [12]:
tco3_events_df

,date,method,definition,data_source,threshold,level_hpa,latitude,lat_band,notes,ozone_onset_DU
0,1980-11-26,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,44.135197
1,1981-09-21,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.728470
2,1981-11-20,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,47.080032
3,1982-10-04,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,42.314781
4,1983-11-03,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.157120
5,1984-11-02,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.721432
6,1986-09-05,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,42.500244
7,1986-11-13,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,45.134018
8,1988-09-24,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.411381
9,1988-10-25,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,45.098133
10,1991-11-18,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.173271
11,1994-08-16,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.583092
12,2000-11-06,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.639286
13,2002-09-22,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,58.906464
14,2003-11-03,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.034882
15,2005-11-12,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,47.487080
16,2012-10-09,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.686127
17,2013-11-02,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.269764
18,2016-11-23,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,40.477310
19,2017-11-07,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,42.184422
20,2019-09-08,ozone_threshold,ozone_du40_-90to-65S,,40.0DU,None,None,"[-90.0, -65.0]",min_persist=3d; min_gap=20d,41.131966

2. u wind decel

In [13]:
# open sample total column ozone data
u1060_path =  os.getcwd()+ "/data/" +"u1060s_era5_1959_2023.nc"
xu1060 = xr.open_dataset(u1060_path)

In [14]:
xu1060

<xarray.Dataset> Size: 1MB
Dimensions:  (time: 94964)
Coordinates:
  * time     (time) datetime64[ns] 760kB 1959-01-01 ... 2023-12-31T18:00:00
    lat      float64 8B ...
    plev     float64 8B ...
Data variables:
    u1060S   (time) float32 380kB ...

In [15]:
time_dim ="time"

In [16]:
# select years
da = xu1060['u1060S'].sel(time=slice(*years))
da = da.resample({time_dim: "1D"}).mean()

In [19]:
percentile=90

In [20]:
# detect events
u1060_events_df, u1060_dates = ssw.detect_u_decel_events(da, percentile=percentile)

In [21]:
u1060_dates

DatetimeIndex(['1982-10-11', '1983-10-03', '1983-11-04', '1985-10-07',
               '1988-09-02', '1988-09-29', '1990-09-29', '1991-09-06',
               '1992-10-06', '1993-10-22', '1994-09-17', '1995-10-14',
               '1997-11-07', '2000-10-02', '2002-09-28', '2003-10-12',
               '2005-10-09', '2007-09-21', '2009-10-15', '2012-10-10',
               '2013-10-20', '2014-09-17', '2014-10-12', '2017-09-14',
               '2019-09-04'],
              dtype='datetime64[ns]', freq=None)

In [22]:
u1060_events_df

,date,method,definition,data_source,threshold,level_hpa,latitude,lat_band,notes,drop_val,window_days
0,1982-10-11,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-30.042351,10.0
1,1983-10-03,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-29.327171,10.0
2,1983-11-04,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-33.234482,10.0
3,1985-10-07,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-31.598831,10.0
4,1988-09-02,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-34.618355,10.0
5,1988-09-29,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-39.179878,10.0
6,1990-09-29,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-46.030037,10.0
7,1991-09-06,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-28.843788,10.0
8,1992-10-06,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-30.062557,10.0
9,1993-10-22,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-29.302975,10.0
10,1994-09-17,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-30.578114,10.0
11,1995-10-14,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-32.365665,10.0
12,1997-11-07,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-42.068127,10.0
13,2000-10-02,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-28.241379,10.0
14,2002-09-28,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-77.199249,10.0
15,2003-10-12,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-32.565739,10.0
16,2005-10-09,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-34.542175,10.0
17,2007-09-21,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-39.953613,10.0
18,2009-10-15,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-28.549931,10.0
19,2012-10-10,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-29.382416,10.0
20,2013-10-20,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-30.119247,10.0
21,2014-09-17,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-32.711235,10.0
22,2014-10-12,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-36.289238,10.0
23,2017-09-14,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-28.807804,10.0
24,2019-09-04,u_wind_decel,decel_percentile_90_wdw10_ratio1.2_thr-2.82/day,,-2.824138,None,None,<NA>,; min_gap=20d; window≈10.00d,-31.781330,10.0